apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kivera.fullname" . }}-conf
  labels:
    app: {{ template "kivera.name" . }}
    chart: {{ template "kivera.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  credentials.json: |-
    {{- .Values.credentials | nindent 4 -}}
