apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "kivera.fullname" . }}-creds
  labels:
    app: {{ template "kivera.name" . }}
    chart: {{ template "kivera.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
stringData:
  credentials.json: |-
    {{- .Values.credentials | nindent 4 -}}
