apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kivera.fullname" . }}
  labels:
    app: {{ template "kivera.name" . }}
    chart: {{ template "kivera.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  apiService:
          create: true
  selector:
    matchLabels:
      app: {{ template "kivera.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "kivera.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ ternary "Always" "IfNotPresent" (eq .Values.image.tag "latest") }}
        resources:
        {{ toYaml .Values.resources | indent 10 }}
        ports:
        - name: proxy-port
          containerPort: {{ .Values.service.proxyPort }}
          protocol: TCP
        - name: mgmt-port
          containerPort: {{ .Values.service.mgmtPort }}
          protocol: TCP
        volumeMounts:
        - name: credentials
          mountPath: /opt/kivera/etc/credentials.json
          subPath: credentials.json
        {{ if .Values.pubCert }}
        - name: pub-cert
          mountPath: /opt/kivera/etc/ca-cert.pem
          subPath: ca-cert.pem
        {{ end }}
        {{ if .Values.pvtKey }}
        - name: pvt-key
          mountPath: /opt/kivera/etc/ca.pem
          subPath: ca.pem
        {{ end }}
        livenessProbe:
          tcpSocket:
            port: mgmt-port
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: mgmt-port
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: credentials
        secret:
          secretName: {{ template "kivera.fullname" . }}-creds
      {{ if .Values.pubCert }}
      - name: pub-cert
        configMap:
          name: {{ template "kivera.fullname" . }}-pub-cert
      {{ end }}
      {{ if .Values.pvtKey }}
      - name: pvt-key
        secret:
          secretName: {{ template "kivera.fullname" . }}-pvt-key
      {{ end }}
