apiVersion: v1
kind: Service
metadata:
  name: {{ template "kivera.fullname" . }}
  labels:
    app: {{ template "kivera.name" . }}
    chart: {{ template "kivera.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
  externalTrafficPolicy: "{{ .Values.service.externalTrafficPolicy }}"
{{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
  ports:
    - port: {{ .Values.service.proxyPort }}
      name: proxy-port
      targetPort: proxy-port
      protocol: TCP
    - port: {{ .Values.service.mgmtPort }}
      name: mgmt-port
      targetPort: mgmt-port
      protocol: TCP
  selector:
    app: {{ template "kivera.name" . }}
    release: {{ .Release.Name }}
