---
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: public.ecr.aws/kivera/kivera-proxy
  tag: latest
  pullPolicy: Always

hpa:
  enabled: true
  maxReplicas: 10
  cpu: 50
  memory: 50

service:
  type: CluserIP
  proxyPort: 8080
  mgmtPort: 8090
  #  Specify IP to whitelist if needed
  #loadBalancerSourceRanges: ""
  # Specify external IP if needed
  #loadBalancerIP: ""

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi