# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: public.ecr.aws/kivera/kivera-proxy
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  proxyPort: 8080
  mgmtPort: 8090
  #  Specify IP to whitelist if needed
  #loadBalancerSourceRanges: ""
  # Specify external IP if needed
  #loadBalancerIP: ""

