---
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: public.ecr.aws/kivera/kivera-proxy
  tag: latest
  pullPolicy: Always

hpa:
  enabled: true
  maxReplicas: 3
  cpu: 50
  memory: 50

service:
  type: LoadBalancer
  proxyPort: 8080
  mgmtPort: 8090
  #  Specify IP to whitelist if needed
  #loadBalancerSourceRanges: ""
  # Specify external IP if needed
  #loadBalancerIP: ""

